// Mocks generated by Mockito 5.4.0 from annotations
// in capstone_project/test/view/screen/transaction/transaction_view_model_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:capstone_project/model/service/transactions_service.dart'
    as _i3;
import 'package:capstone_project/model/transactions_model.dart' as _i5;
import 'package:dio/dio.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeDio_0 extends _i1.SmartFake implements _i2.Dio {
  _FakeDio_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [TransactionsService].
///
/// See the documentation for Mockito's code generation for more information.
class MockTransactionsService extends _i1.Mock
    implements _i3.TransactionsService {
  MockTransactionsService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.Dio get dio => (super.noSuchMethod(
        Invocation.getter(#dio),
        returnValue: _FakeDio_0(
          this,
          Invocation.getter(#dio),
        ),
      ) as _i2.Dio);
  @override
  _i4.Future<List<_i5.TransactionsModel>> getAllTransactions({
    required String? token,
    required bool? statusOngoing,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAllTransactions,
          [],
          {
            #token: token,
            #statusOngoing: statusOngoing,
          },
        ),
        returnValue: _i4.Future<List<_i5.TransactionsModel>>.value(
            <_i5.TransactionsModel>[]),
      ) as _i4.Future<List<_i5.TransactionsModel>>);
  @override
  _i4.Future<List<_i5.TransactionsModel>> getAllTransactionsBySearch({
    required String? token,
    required bool? statusOngoing,
    required String? search,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAllTransactionsBySearch,
          [],
          {
            #token: token,
            #statusOngoing: statusOngoing,
            #search: search,
          },
        ),
        returnValue: _i4.Future<List<_i5.TransactionsModel>>.value(
            <_i5.TransactionsModel>[]),
      ) as _i4.Future<List<_i5.TransactionsModel>>);
  @override
  _i4.Future<String> postReviewCounselor({
    required String? token,
    required String? counselorId,
    required String? transactionId,
    required int? rating,
    required String? review,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #postReviewCounselor,
          [],
          {
            #token: token,
            #counselorId: counselorId,
            #transactionId: transactionId,
            #rating: rating,
            #review: review,
          },
        ),
        returnValue: _i4.Future<String>.value(''),
      ) as _i4.Future<String>);
  @override
  _i4.Future<String> postUserJoinTransaction({
    required String? token,
    required String? userId,
    required String? transactionId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #postUserJoinTransaction,
          [],
          {
            #token: token,
            #userId: userId,
            #transactionId: transactionId,
          },
        ),
        returnValue: _i4.Future<String>.value(''),
      ) as _i4.Future<String>);
}
